name = "IntegralConformalMap"
uuid = "c8fb8e27-76f2-49a6-b57b-4ca81aac0aba"
authors = ["Veenty <vgh225@nyu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
