name = "IntegralConformalMap"
uuid = "c8fb8e27-76f2-49a6-b57b-4ca81aac0aba"
authors = ["Veenty <vgh225@nyu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"

[compat]
FFTW = "1.8.1"
Krylov = "0.9.10"
LinearOperators = "2.9.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
